name: Elixir CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:   
    - name: Run tests
      run: mix test
    - name: Run credo
      run: mix credo
    - name: Cheeck formatting
      run: mix format --check-formatted
